# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'control.ui'
#
# Created by: PyQt5 UI code generator 5.15.5
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 511)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 771, 211))
        self.groupBox.setObjectName("groupBox")
        self.pushButton_respawn = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_respawn.setGeometry(QtCore.QRect(90, 30, 121, 51))
        self.pushButton_respawn.setObjectName("pushButton_respawn")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 30, 81, 51))
        self.label.setObjectName("label")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 230, 771, 211))
        self.groupBox_2.setObjectName("groupBox_2")
        self.pushButton_conveyor_speed = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_conveyor_speed.setGeometry(QtCore.QRect(350, 40, 121, 51))
        self.pushButton_conveyor_speed.setObjectName("pushButton_conveyor_speed")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setGeometry(QtCore.QRect(10, 46, 181, 41))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setGeometry(QtCore.QRect(310, 46, 31, 41))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.plainTextEdit_conveyor_speed = QtWidgets.QPlainTextEdit(self.groupBox_2)
        self.plainTextEdit_conveyor_speed.setGeometry(QtCore.QRect(200, 40, 104, 51))
        self.plainTextEdit_conveyor_speed.setObjectName("plainTextEdit_conveyor_speed")
        self.groupBox_2.raise_()
        self.groupBox.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Object Spawn"))
        self.pushButton_respawn.setText(_translate("MainWindow", "Respawn"))
        self.label.setText(_translate("MainWindow", "3 Blocks :"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Conveyor Belt Control"))
        self.pushButton_conveyor_speed.setText(_translate("MainWindow", "Send Command"))
        self.label_2.setText(_translate("MainWindow", "Conveyor Speed Control :"))
        self.label_3.setText(_translate("MainWindow", "%"))
