# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'control.ui'
#
# Created by: PyQt5 UI code generator 5.15.5
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(670, 226)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 241, 161))
        self.groupBox.setObjectName("groupBox")
        self.pushButton_respawn = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_respawn.setGeometry(QtCore.QRect(90, 30, 141, 51))
        self.pushButton_respawn.setObjectName("pushButton_respawn")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 30, 81, 51))
        self.label.setObjectName("label")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(10, 100, 71, 51))
        self.label_4.setObjectName("label_4")
        self.pushButton_delete_all = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_delete_all.setGeometry(QtCore.QRect(90, 100, 141, 51))
        self.pushButton_delete_all.setObjectName("pushButton_delete_all")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(270, 10, 271, 161))
        self.groupBox_2.setObjectName("groupBox_2")
        self.pushButton_conveyor_speed = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_conveyor_speed.setGeometry(QtCore.QRect(140, 100, 121, 51))
        self.pushButton_conveyor_speed.setObjectName("pushButton_conveyor_speed")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setGeometry(QtCore.QRect(10, 30, 121, 51))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setGeometry(QtCore.QRect(240, 30, 31, 51))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.plainTextEdit_conveyor_speed = QtWidgets.QPlainTextEdit(self.groupBox_2)
        self.plainTextEdit_conveyor_speed.setGeometry(QtCore.QRect(140, 30, 104, 51))
        self.plainTextEdit_conveyor_speed.setObjectName("plainTextEdit_conveyor_speed")
        self.pushButton_conveyor_stop = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_conveyor_stop.setGeometry(QtCore.QRect(10, 100, 121, 51))
        self.pushButton_conveyor_stop.setObjectName("pushButton_conveyor_stop")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(560, 10, 101, 161))
        self.groupBox_3.setObjectName("groupBox_3")
        self.label_7 = QtWidgets.QLabel(self.groupBox_3)
        self.label_7.setGeometry(QtCore.QRect(10, 30, 41, 51))
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.groupBox_3)
        self.label_8.setGeometry(QtCore.QRect(50, 30, 41, 51))
        self.label_8.setText("")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.groupBox_2.raise_()
        self.groupBox.raise_()
        self.groupBox_3.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 670, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Fruit Sorter Control Panel"))
        self.groupBox.setTitle(_translate("MainWindow", "Object Spawn"))
        self.pushButton_respawn.setText(_translate("MainWindow", "Respawn"))
        self.label.setText(_translate("MainWindow", "3 Blocks :"))
        self.label_4.setText(_translate("MainWindow", "Random :"))
        self.pushButton_delete_all.setText(_translate("MainWindow", "Delete All Blocks"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Conveyor Belt Control"))
        self.pushButton_conveyor_speed.setText(_translate("MainWindow", "Send Command"))
        self.label_2.setText(_translate("MainWindow", "Speed Control  :"))
        self.label_3.setText(_translate("MainWindow", "%"))
        self.pushButton_conveyor_stop.setText(_translate("MainWindow", "Stop Conveyor"))
        self.groupBox_3.setTitle(_translate("MainWindow", "AprilTag"))
        self.label_7.setText(_translate("MainWindow", "ID : "))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
